package store

import (
	"context"
	"database/sql"
	"errors"
)

// Client is a subscriber that may be granted access to inbounds.
type Client struct {
	ID                int64
	Name              string
	UUID              string
	Password          string
	SubscriptionToken string
	Enabled           bool
	Remark            string
	Email             string
	TelegramChatID    string // numeric chat id once the client links their Telegram
	TelegramUsername  string // @handle, display only
	TelegramLinkToken string // deep-link payload that binds a chat to this client
	WalletKopecks     int64  // prepaid balance in kopecks (100 = 1 RUB)
	ActiveUntil       string // subscription expiry (RFC3339); "" = no billed subscription
	BillingManaged    bool   // true once the client has bought a subscription
	BillingExempt     bool   // lifetime free access: never auto-suspended
	CreatedAt         string
	UpdatedAt         string
}

// ClientParams holds the writable/generated fields for create.
type ClientParams struct {
	Name              string
	UUID              string
	Password          string
	SubscriptionToken string
	Enabled           bool
	Remark            string
	Email             string
	TelegramLinkToken string
}

// ClientGrant is an inbound granted to a client, with server context, as shown
// in the UI. It does not carry the full inbound settings.
type ClientGrant struct {
	InboundID    int64
	ServerID     int64
	ServerName   string
	ServerHost   string
	InboundTag   string
	Protocol     string
	InboundOn    bool // inbounds.enabled
	GrantEnabled bool // client_inbounds.enabled
}

// InboundWithServer carries a full inbound plus its server host/name, used to
// build subscription URIs and engine configs.
type InboundWithServer struct {
	Inbound
	ServerName string
	ServerHost string
}

const clientSelect = `
	SELECT id, name, uuid, password, subscription_token, enabled, remark, created_at, updated_at, email,
	       tg_chat_id, tg_username, tg_link_token, wallet_kopecks, active_until, billing_managed, billing_exempt
	FROM clients`

func scanClient(sc interface{ Scan(...any) error }) (*Client, error) {
	var c Client
	var enabled, managed, exempt int64
	err := sc.Scan(&c.ID, &c.Name, &c.UUID, &c.Password, &c.SubscriptionToken,
		&enabled, &c.Remark, &c.CreatedAt, &c.UpdatedAt, &c.Email,
		&c.TelegramChatID, &c.TelegramUsername, &c.TelegramLinkToken,
		&c.WalletKopecks, &c.ActiveUntil, &managed, &exempt)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	c.Enabled = enabled != 0
	c.BillingManaged = managed != 0
	c.BillingExempt = exempt != 0
	return &c, nil
}

// SetClientBillingExempt grants or revokes lifetime free access.
func (s *Store) SetClientBillingExempt(ctx context.Context, id int64, exempt bool) (*Client, error) {
	res, err := s.db.ExecContext(ctx,
		"UPDATE clients SET billing_exempt = ?, updated_at = ? WHERE id = ?",
		boolToInt(exempt), nowRFC3339(), id)
	if err != nil {
		return nil, err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return nil, ErrNotFound
	}
	return s.GetClient(ctx, id)
}

// ListClients returns all clients, oldest first.
func (s *Store) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := s.db.QueryContext(ctx, clientSelect+" ORDER BY id ASC")
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	var out []Client
	for rows.Next() {
		c, err := scanClient(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *c)
	}
	return out, rows.Err()
}

// GetClient returns a client by id.
func (s *Store) GetClient(ctx context.Context, id int64) (*Client, error) {
	return scanClient(s.db.QueryRowContext(ctx, clientSelect+" WHERE id = ?", id))
}

// GetClientByToken returns a client by its subscription token.
func (s *Store) GetClientByToken(ctx context.Context, token string) (*Client, error) {
	return scanClient(s.db.QueryRowContext(ctx, clientSelect+" WHERE subscription_token = ?", token))
}

// CreateClient inserts a client (uuid/password/token are generated by the caller).
func (s *Store) CreateClient(ctx context.Context, p ClientParams) (*Client, error) {
	now := nowRFC3339()
	res, err := s.db.ExecContext(ctx, `
		INSERT INTO clients (name, uuid, password, subscription_token, enabled, remark, email, tg_link_token, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		p.Name, p.UUID, p.Password, p.SubscriptionToken, boolToInt(p.Enabled), p.Remark, p.Email, p.TelegramLinkToken, now, now)
	if err != nil {
		return nil, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return nil, err
	}
	return s.GetClient(ctx, id)
}

// UpdateClient changes the name, remark and contact e-mail.
func (s *Store) UpdateClient(ctx context.Context, id int64, name, remark, email string) (*Client, error) {
	if _, err := s.db.ExecContext(ctx,
		"UPDATE clients SET name=?, remark=?, email=?, updated_at=? WHERE id=?",
		name, remark, email, nowRFC3339(), id); err != nil {
		return nil, err
	}
	return s.GetClient(ctx, id)
}

// SetClientTelegramLinkToken stores the deep-link token that binds a Telegram
// chat to this client.
func (s *Store) SetClientTelegramLinkToken(ctx context.Context, id int64, token string) error {
	res, err := s.db.ExecContext(ctx,
		"UPDATE clients SET tg_link_token=?, updated_at=? WHERE id=?", token, nowRFC3339(), id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// LinkClientTelegram binds a Telegram chat (and optional @username) to the client
// that owns linkToken, returning the updated client. An empty token never matches
// so clients that haven't generated one can't be hijacked by a bare /start.
func (s *Store) LinkClientTelegram(ctx context.Context, linkToken, chatID, username string) (*Client, error) {
	if linkToken == "" {
		return nil, ErrNotFound
	}
	c, err := scanClient(s.db.QueryRowContext(ctx, clientSelect+" WHERE tg_link_token = ?", linkToken))
	if err != nil {
		return nil, err
	}
	if _, err := s.db.ExecContext(ctx,
		"UPDATE clients SET tg_chat_id=?, tg_username=?, updated_at=? WHERE id=?",
		chatID, username, nowRFC3339(), c.ID); err != nil {
		return nil, err
	}
	return s.GetClient(ctx, c.ID)
}

// GetClientByTelegramChatID returns the client whose Telegram chat is bound to
// chatID (used to answer a linked client's in-bot config requests). An empty
// chatID never matches.
func (s *Store) GetClientByTelegramChatID(ctx context.Context, chatID string) (*Client, error) {
	if chatID == "" {
		return nil, ErrNotFound
	}
	return scanClient(s.db.QueryRowContext(ctx, clientSelect+" WHERE tg_chat_id = ?", chatID))
}

// ClearClientTelegram unlinks a client's Telegram chat.
func (s *Store) ClearClientTelegram(ctx context.Context, id int64) (*Client, error) {
	res, err := s.db.ExecContext(ctx,
		"UPDATE clients SET tg_chat_id='', tg_username='', updated_at=? WHERE id=?", nowRFC3339(), id)
	if err != nil {
		return nil, err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return nil, ErrNotFound
	}
	return s.GetClient(ctx, id)
}

// SetClientEnabled toggles a client on/off without deleting it.
func (s *Store) SetClientEnabled(ctx context.Context, id int64, enabled bool) (*Client, error) {
	res, err := s.db.ExecContext(ctx,
		"UPDATE clients SET enabled=?, updated_at=? WHERE id=?",
		boolToInt(enabled), nowRFC3339(), id)
	if err != nil {
		return nil, err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return nil, ErrNotFound
	}
	return s.GetClient(ctx, id)
}

// RotateClientToken replaces the subscription token.
func (s *Store) RotateClientToken(ctx context.Context, id int64, token string) (*Client, error) {
	res, err := s.db.ExecContext(ctx,
		"UPDATE clients SET subscription_token=?, updated_at=? WHERE id=?",
		token, nowRFC3339(), id)
	if err != nil {
		return nil, err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return nil, ErrNotFound
	}
	return s.GetClient(ctx, id)
}

// DeleteClient removes a client (cascades to grants).
func (s *Store) DeleteClient(ctx context.Context, id int64) error {
	res, err := s.db.ExecContext(ctx, "DELETE FROM clients WHERE id = ?", id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

// GrantedInboundIDs returns the inbound ids granted to a client (any grant row).
func (s *Store) GrantedInboundIDs(ctx context.Context, clientID int64) ([]int64, error) {
	rows, err := s.db.QueryContext(ctx,
		"SELECT inbound_id FROM client_inbounds WHERE client_id = ? ORDER BY inbound_id ASC", clientID)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	out := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		out = append(out, id)
	}
	return out, rows.Err()
}

// SetClientInbounds replaces a client's grants with the given desired set. Grant
// rows are enabled by default. Unknown inbound ids are ignored by the FK.
func (s *Store) SetClientInbounds(ctx context.Context, clientID int64, inboundIDs []int64) error {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()

	if _, err := tx.ExecContext(ctx, "DELETE FROM client_inbounds WHERE client_id = ?", clientID); err != nil {
		return err
	}
	now := nowRFC3339()
	for _, inb := range inboundIDs {
		if _, err := tx.ExecContext(ctx, `
			INSERT INTO client_inbounds (client_id, inbound_id, enabled, created_at)
			VALUES (?, ?, 1, ?)`, clientID, inb, now); err != nil {
			return err
		}
	}
	return tx.Commit()
}

const clientGrantSelect = `
	SELECT ci.inbound_id, s.id, s.name, s.host, i.tag, i.protocol, i.enabled, ci.enabled
	FROM client_inbounds ci
	JOIN inbounds i ON i.id = ci.inbound_id
	JOIN servers  s ON s.id = i.server_id
	WHERE ci.client_id = ?
	ORDER BY s.id ASC, i.id ASC`

// ListClientGrants returns a client's grants with server/inbound context.
func (s *Store) ListClientGrants(ctx context.Context, clientID int64) ([]ClientGrant, error) {
	rows, err := s.db.QueryContext(ctx, clientGrantSelect, clientID)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	out := []ClientGrant{}
	for rows.Next() {
		var g ClientGrant
		var inboundOn, grantOn int64
		if err := rows.Scan(&g.InboundID, &g.ServerID, &g.ServerName, &g.ServerHost,
			&g.InboundTag, &g.Protocol, &inboundOn, &grantOn); err != nil {
			return nil, err
		}
		g.InboundOn = inboundOn != 0
		g.GrantEnabled = grantOn != 0
		out = append(out, g)
	}
	return out, rows.Err()
}

// inboundWithServerSelect projects a full inbound plus its server host/name.
const inboundWithServerSelect = `
	SELECT i.id, i.server_id, i.tag, i.protocol, i.listen, i.port,
	       i.settings_json, i.stream_settings_json, i.sniffing_json, i.remark, i.enabled,
	       i.created_at, i.updated_at,
	       (SELECT COUNT(*) FROM client_inbounds WHERE inbound_id = i.id) AS client_count,
	       s.host, s.name
	FROM inbounds i
	JOIN servers s ON s.id = i.server_id`

// ListActiveClientInbounds returns the full inbounds a client should appear in:
// grant enabled AND inbound enabled. Used to build subscription URIs. The client
// being disabled is the caller's responsibility to check.
func (s *Store) ListActiveClientInbounds(ctx context.Context, clientID int64) ([]InboundWithServer, error) {
	rows, err := s.db.QueryContext(ctx, inboundWithServerSelect+`
		JOIN client_inbounds ci ON ci.inbound_id = i.id
		WHERE ci.client_id = ? AND ci.enabled = 1 AND i.enabled = 1
		ORDER BY s.id ASC, i.id ASC`, clientID)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	return scanInboundsWithServer(rows)
}

// ListInboundGrantedClients returns the enabled clients that hold an enabled
// grant to an inbound. Used by sync to assemble each engine's config.
func (s *Store) ListInboundGrantedClients(ctx context.Context, inboundID int64) ([]Client, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT c.id, c.name, c.uuid, c.password, c.subscription_token, c.enabled, c.remark,
		       c.created_at, c.updated_at, c.email, c.tg_chat_id, c.tg_username, c.tg_link_token,
		       c.wallet_kopecks, c.active_until, c.billing_managed, c.billing_exempt
		FROM client_inbounds ci
		JOIN clients c ON c.id = ci.client_id
		WHERE ci.inbound_id = ? AND ci.enabled = 1 AND c.enabled = 1
		ORDER BY c.id ASC`, inboundID)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	var out []Client
	for rows.Next() {
		c, err := scanClient(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *c)
	}
	return out, rows.Err()
}

// scanInboundsWithServer scans rows selected via inboundSelect joined with the
// server host/name appended as the last two columns.
func scanInboundsWithServer(rows *sql.Rows) ([]InboundWithServer, error) {
	out := []InboundWithServer{}
	for rows.Next() {
		var in Inbound
		var enabled int64
		var host, name string
		if err := rows.Scan(&in.ID, &in.ServerID, &in.Tag, &in.Protocol, &in.Listen, &in.Port,
			&in.SettingsJSON, &in.StreamSettingsJSON, &in.SniffingJSON, &in.Remark, &enabled,
			&in.CreatedAt, &in.UpdatedAt, &in.ClientCount, &host, &name); err != nil {
			return nil, err
		}
		in.Enabled = enabled != 0
		out = append(out, InboundWithServer{Inbound: in, ServerHost: host, ServerName: name})
	}
	return out, rows.Err()
}

// GetClientParams returns the client's per-client protocol params JSON blob
// (defaults to "{}" for a client that has none yet).
func (s *Store) GetClientParams(ctx context.Context, id int64) (string, error) {
	var v string
	err := s.db.QueryRowContext(ctx, "SELECT params_json FROM clients WHERE id = ?", id).Scan(&v)
	if errors.Is(err, sql.ErrNoRows) {
		return "", ErrNotFound
	}
	if err != nil {
		return "", err
	}
	if v == "" {
		v = "{}"
	}
	return v, nil
}

// SetClientParams writes the client's per-client protocol params JSON blob.
func (s *Store) SetClientParams(ctx context.Context, id int64, paramsJSON string) error {
	res, err := s.db.ExecContext(ctx, "UPDATE clients SET params_json = ? WHERE id = ?", paramsJSON, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}
