package httpapi

import (
	"encoding/json"
	"net/http"
	"strings"
	"testing"
)

func TestInbounds_CRUDAndRealityKeys(t *testing.T) {
	env := newTestEnv(t)
	seedAdmin(t, env)
	token := loginToken(t, env)
	srv := createServer(t, env, token, "s1")
	base := "/api/servers/" + itoa(srv.ID) + "/inbounds"

	// create a VLESS Reality inbound with placeholder keys — backend must fill them
	body := map[string]any{
		"tag": "vless-reality", "protocol": "vless", "port": 443,
		"settings": map[string]any{"flow": "xtls-rprx-vision", "decryption": "none"},
		"stream_settings": map[string]any{
			"network": "tcp", "security": "reality",
			"realitySettings": map[string]any{
				"dest": "www.yahoo.com:443", "serverNames": []string{"www.yahoo.com"},
				"privateKey": "<generated by backend>", "shortIds": []string{},
				"fingerprint": "chrome", "spiderX": "/",
			},
		},
		"sniffing": map[string]any{"enabled": true, "destOverride": []string{"http", "tls", "quic"}},
	}
	rec := env.do(t, http.MethodPost, base, token, body)
	if rec.Code != http.StatusCreated {
		t.Fatalf("create status = %d, body %s", rec.Code, rec.Body.String())
	}
	var created inboundDTO
	_ = json.Unmarshal(rec.Body.Bytes(), &created)
	if created.Engine != "xray" {
		t.Errorf("engine = %q, want xray", created.Engine)
	}
	// reality keys generated on the backend
	var stream map[string]any
	_ = json.Unmarshal(created.StreamSettings, &stream)
	rs, _ := stream["realitySettings"].(map[string]any)
	priv, _ := rs["privateKey"].(string)
	pub, _ := rs["publicKey"].(string)
	if priv == "" || strings.HasPrefix(priv, "<") {
		t.Errorf("privateKey not generated: %q", priv)
	}
	if pub == "" {
		t.Error("publicKey not generated")
	}
	sids, _ := rs["shortIds"].([]any)
	if len(sids) == 0 {
		t.Error("shortIds not generated")
	}

	// list
	rec = env.do(t, http.MethodGet, base, token, nil)
	var list []inboundDTO
	_ = json.Unmarshal(rec.Body.Bytes(), &list)
	if len(list) != 1 {
		t.Fatalf("list len = %d", len(list))
	}

	// update (toggle disabled)
	upd := map[string]any{"tag": "vless-reality", "protocol": "vless", "port": 443, "enabled": false}
	rec = env.do(t, http.MethodPut, "/api/inbounds/"+itoa(created.ID), token, upd)
	if rec.Code != http.StatusOK {
		t.Fatalf("update status = %d", rec.Code)
	}
	var updated inboundDTO
	_ = json.Unmarshal(rec.Body.Bytes(), &updated)
	if updated.Enabled {
		t.Error("expected disabled after update")
	}

	// delete
	rec = env.do(t, http.MethodDelete, "/api/inbounds/"+itoa(created.ID), token, nil)
	if rec.Code != http.StatusNoContent {
		t.Fatalf("delete status = %d", rec.Code)
	}
}

func TestInbounds_UnknownProtocol(t *testing.T) {
	env := newTestEnv(t)
	seedAdmin(t, env)
	token := loginToken(t, env)
	srv := createServer(t, env, token, "s1")
	rec := env.do(t, http.MethodPost, "/api/servers/"+itoa(srv.ID)+"/inbounds", token,
		map[string]any{"tag": "x", "protocol": "wireguard", "port": 51820})
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("status = %d, want 400", rec.Code)
	}
}

func TestInbounds_HysteriaEngine(t *testing.T) {
	env := newTestEnv(t)
	seedAdmin(t, env)
	token := loginToken(t, env)
	srv := createServer(t, env, token, "s1")
	rec := env.do(t, http.MethodPost, "/api/servers/"+itoa(srv.ID)+"/inbounds", token, map[string]any{
		"tag": "hy2", "protocol": "hysteria2", "port": 36712,
		"settings": map[string]any{"up": "100 mbps", "down": "200 mbps"},
	})
	if rec.Code != http.StatusCreated {
		t.Fatalf("status = %d, body %s", rec.Code, rec.Body.String())
	}
	var dto inboundDTO
	_ = json.Unmarshal(rec.Body.Bytes(), &dto)
	if dto.Engine != "hysteria" {
		t.Errorf("engine = %q, want hysteria", dto.Engine)
	}
}
