// Structured inbound settings modelled after 3x-ui / xray-core, so the form can
// show sensible, editable defaults and build the settings/stream_settings JSON.
// Client identities (uuid/password) and Reality key pairs are generated by the
// backend — they are intentionally not part of this form.
import type { Protocol } from '@/api/types'

export type Network = 'tcp' | 'ws' | 'grpc' | 'httpupgrade' | 'xhttp'
export type Security = 'none' | 'tls' | 'reality'

export const NETWORKS: Network[] = ['tcp', 'ws', 'grpc', 'httpupgrade', 'xhttp']
export const FINGERPRINTS = ['chrome', 'firefox', 'safari', 'ios', 'android', 'edge', 'random', 'randomized']
export const SS_METHODS = [
  '2022-blake3-aes-256-gcm',
  '2022-blake3-aes-128-gcm',
  '2022-blake3-chacha20-poly1305',
  'aes-256-gcm',
  'aes-128-gcm',
  'chacha20-ietf-poly1305',
  'xchacha20-ietf-poly1305',
]
export const VMESS_CIPHERS = ['auto', 'aes-128-gcm', 'chacha20-poly1305', 'none', 'zero']
export const SNIFF_OVERRIDES = ['http', 'tls', 'quic', 'fakedns']

// Which securities each protocol may use.
export function securitiesFor(protocol: Protocol): Security[] {
  if (protocol === 'vless') return ['reality', 'tls', 'none']
  if (protocol === 'vmess' || protocol === 'trojan') return ['tls', 'none']
  return []
}

export interface InboundForm {
  tag: string
  protocol: Protocol
  listen: string
  port: string
  remark: string
  enabled: boolean

  // xray transport / security
  network: Network
  security: Security
  flow: string // vless only: '' | 'xtls-rprx-vision'
  // ws / httpupgrade / xhttp
  path: string
  host: string
  // grpc
  grpcServiceName: string
  grpcMultiMode: boolean
  // tcp
  tcpHeaderType: 'none' | 'http'
  // tls
  sni: string
  alpn: string // comma separated
  fingerprint: string
  // reality
  realityDest: string
  realityServerNames: string // comma separated
  realityShortIds: string // comma separated ('' → backend generates)
  realitySpiderX: string
  // vmess
  vmessCipher: string
  // shadowsocks
  ssMethod: string
  ssNetwork: string // 'tcp,udp'
  // hysteria2
  hyUp: string
  hyDown: string
  hyObfsType: 'none' | 'salamander'
  hyObfsPassword: string
  hyInsecure: boolean

  // sniffing
  sniffEnabled: boolean
  sniffOverrides: string[]
}

export function emptyForm(): InboundForm {
  return {
    tag: '',
    protocol: 'vless',
    listen: '0.0.0.0',
    port: '',
    remark: '',
    enabled: true,
    network: 'tcp',
    security: 'reality',
    flow: 'xtls-rprx-vision',
    path: '/',
    host: '',
    grpcServiceName: '',
    grpcMultiMode: false,
    tcpHeaderType: 'none',
    sni: '',
    alpn: 'h2,http/1.1',
    fingerprint: 'chrome',
    realityDest: 'www.microsoft.com:443',
    realityServerNames: 'www.microsoft.com',
    realityShortIds: '',
    realitySpiderX: '/',
    vmessCipher: 'auto',
    ssMethod: '2022-blake3-aes-256-gcm',
    ssNetwork: 'tcp,udp',
    hyUp: '100',
    hyDown: '100',
    hyObfsType: 'none',
    hyObfsPassword: '',
    hyInsecure: true,
    sniffEnabled: true,
    sniffOverrides: ['http', 'tls', 'quic'],
  }
}

// Per-protocol defaults applied when the user switches protocol, so the form is
// pre-filled with a working, visible configuration.
export function protocolDefaults(protocol: Protocol): Partial<InboundForm> {
  switch (protocol) {
    case 'vless':
      return {
        port: '443',
        network: 'tcp',
        security: 'reality',
        flow: 'xtls-rprx-vision',
        realityDest: 'www.microsoft.com:443',
        realityServerNames: 'www.microsoft.com',
        fingerprint: 'chrome',
        realitySpiderX: '/',
      }
    case 'vmess':
      return { port: '10000', network: 'ws', security: 'none', flow: '', path: '/vm', host: '' }
    case 'trojan':
      return { port: '443', network: 'tcp', security: 'tls', flow: '' }
    case 'shadowsocks':
      return { port: '8388', ssMethod: '2022-blake3-aes-256-gcm', ssNetwork: 'tcp,udp' }
    case 'hysteria2':
      return { port: '36712', hyUp: '100', hyDown: '100', hyObfsType: 'none', hyInsecure: true }
    default:
      return {}
  }
}

function splitList(s: string): string[] {
  return s
    .split(',')
    .map((x) => x.trim())
    .filter(Boolean)
}

type Json = Record<string, unknown>

// Build the settings / stream_settings / sniffing objects the backend would store.
export function buildConfig(f: InboundForm): {
  settings: Json
  stream_settings: Json
  sniffing: Json
} {
  let settings: Json = {}
  let stream: Json = {}

  if (f.protocol === 'hysteria2') {
    settings = {
      up: `${f.hyUp || '0'} mbps`,
      down: `${f.hyDown || '0'} mbps`,
      ...(f.hyObfsType !== 'none'
        ? { obfs: { type: f.hyObfsType, password: f.hyObfsPassword || '<generated>' } }
        : {}),
      note: 'auth via each client password',
    }
    stream = {
      security: 'tls',
      tlsSettings: {
        serverName: f.sni || undefined,
        insecure: f.hyInsecure,
        alpn: ['h3'],
      },
    }
    return { settings, stream_settings: stream, sniffing: sniffingObj(f) }
  }

  // ---- xray protocols ----
  switch (f.protocol) {
    case 'vless':
      settings = { decryption: 'none', ...(f.flow ? { flow: f.flow } : {}), clients: '<generated>' }
      break
    case 'vmess':
      settings = { security: f.vmessCipher, clients: '<generated>' }
      break
    case 'trojan':
      settings = { clients: '<generated>' }
      break
    case 'shadowsocks':
      settings = { method: f.ssMethod, network: f.ssNetwork, password: '<generated>' }
      break
  }

  stream = { network: f.network, security: f.security }

  if (f.network === 'ws') stream.wsSettings = { path: f.path || '/', headers: f.host ? { Host: f.host } : {} }
  else if (f.network === 'grpc')
    stream.grpcSettings = { serviceName: f.grpcServiceName, multiMode: f.grpcMultiMode }
  else if (f.network === 'httpupgrade')
    stream.httpupgradeSettings = { path: f.path || '/', host: f.host || undefined }
  else if (f.network === 'xhttp')
    stream.xhttpSettings = { path: f.path || '/', host: f.host || undefined, mode: 'auto' }
  else if (f.network === 'tcp' && f.tcpHeaderType === 'http')
    stream.tcpSettings = { header: { type: 'http' } }

  if (f.security === 'tls') {
    stream.tlsSettings = {
      serverName: f.sni || undefined,
      alpn: splitList(f.alpn),
      fingerprint: f.fingerprint,
    }
  } else if (f.security === 'reality') {
    stream.realitySettings = {
      show: false,
      dest: f.realityDest,
      serverNames: splitList(f.realityServerNames),
      privateKey: '<generated by backend>',
      publicKey: '<generated by backend>',
      shortIds: f.realityShortIds ? splitList(f.realityShortIds) : ['<generated>'],
      fingerprint: f.fingerprint,
      spiderX: f.realitySpiderX || '/',
    }
  }

  return { settings, stream_settings: stream, sniffing: sniffingObj(f) }
}

function sniffingObj(f: InboundForm): Json {
  return { enabled: f.sniffEnabled, destOverride: f.sniffEnabled ? f.sniffOverrides : [] }
}

// Best-effort parse of an existing inbound back into form fields (for editing).
export function parseInbound(
  base: InboundForm,
  settings?: Record<string, unknown>,
  stream?: Record<string, unknown>,
  sniffing?: Record<string, unknown>,
): InboundForm {
  const f = { ...base }
  const s = (settings ?? {}) as any
  const ss = (stream ?? {}) as any
  const sn = (sniffing ?? {}) as any

  if (f.protocol === 'hysteria2') {
    if (typeof s.up === 'string') f.hyUp = s.up.replace(/[^0-9]/g, '') || f.hyUp
    if (typeof s.down === 'string') f.hyDown = s.down.replace(/[^0-9]/g, '') || f.hyDown
    if (s.obfs?.type) {
      f.hyObfsType = 'salamander'
      f.hyObfsPassword = s.obfs.password ?? ''
    }
    if (ss.tlsSettings) {
      f.sni = ss.tlsSettings.serverName ?? f.sni
      f.hyInsecure = !!ss.tlsSettings.insecure
    }
  } else {
    if (ss.network) f.network = ss.network
    if (ss.security) f.security = ss.security
    if (typeof s.flow === 'string') f.flow = s.flow
    if (s.method) f.ssMethod = s.method
    if (s.network) f.ssNetwork = s.network
    if (s.security) f.vmessCipher = s.security
    if (ss.wsSettings) {
      f.path = ss.wsSettings.path ?? f.path
      f.host = ss.wsSettings.headers?.Host ?? f.host
    }
    if (ss.grpcSettings) {
      f.grpcServiceName = ss.grpcSettings.serviceName ?? ''
      f.grpcMultiMode = !!ss.grpcSettings.multiMode
    }
    if (ss.httpupgradeSettings) {
      f.path = ss.httpupgradeSettings.path ?? f.path
      f.host = ss.httpupgradeSettings.host ?? f.host
    }
    if (ss.tcpSettings?.header?.type) f.tcpHeaderType = ss.tcpSettings.header.type
    if (ss.tlsSettings) {
      f.sni = ss.tlsSettings.serverName ?? f.sni
      if (Array.isArray(ss.tlsSettings.alpn)) f.alpn = ss.tlsSettings.alpn.join(',')
      if (ss.tlsSettings.fingerprint) f.fingerprint = ss.tlsSettings.fingerprint
    }
    if (ss.realitySettings) {
      const r = ss.realitySettings
      f.realityDest = r.dest ?? f.realityDest
      if (Array.isArray(r.serverNames)) f.realityServerNames = r.serverNames.join(',')
      if (Array.isArray(r.shortIds)) f.realityShortIds = r.shortIds.filter((x: string) => !x.startsWith('<')).join(',')
      if (r.fingerprint) f.fingerprint = r.fingerprint
      if (r.spiderX) f.realitySpiderX = r.spiderX
    }
  }

  if (typeof sn.enabled === 'boolean') f.sniffEnabled = sn.enabled
  if (Array.isArray(sn.destOverride)) f.sniffOverrides = sn.destOverride

  return f
}
