DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS client_inbounds;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS inbounds;
DROP TABLE IF EXISTS servers;
DROP TABLE IF EXISTS admins;
